name: cross-platform-pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - develop
env:
  GLOBAL_SECRET: $SECRET_TOKEN
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
    env:
      BUILD_ENV: production
    steps:
    - name: install
      run: npm install
    - name: compile
      run: npm run build $BUILD_FLAG
      env:
        BUILD_FLAG: --prod
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test-suite
      run: npm test
    needs:
    - build
