name: Hello Class Pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - develop
env:
  GLOBAL_SECRET: $SECRET_TOKEN
jobs:
  install_packages:
    runs-on: ubuntu-latest
    container:
      image: node:18
    env:
      BUILD_ENV: production
    steps:
    - name: install
      run: echo "Installing dependencies..." && sleep 5
    - name: packeges installed
      run: echo "Dependencies installed successfully!" && echo "Hello, Class!"
  build_stuff:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
    - name: install packages again
      run: echo "Building stuff" && sleep 10
    - name: build project
      run: echo "Stuff has been built"
  test:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
    - name: component tests
      run: echo "Running component tests" && sleep 5
    - name: e2e tests
      run: echo "Running end-to-end tests" && sleep 5
    - name: integration tests
      run: echo "Running integration tests" && sleep 5
    - name: run succesful
      run: echo "Tests completed successfully!"
