on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - develop
env:
  GLOBAL_SECRET: $SECRET_TOKEN
jobs:
  install:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production
    steps:
    - name: install packages
      run: echo "Installing dependencies..." && sleep 10
    - name: packeged installed
      run: echo "Dependencies installed successfully!"
  linting:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production
    steps:
    - name: lint code
      run: echo "linting code..." && sleep 10
    - name: packeged installed
      run: echo "Code linted successfully!"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: create build
      run: echo "Building project..." && sleep 10
    - name: build created
      run: echo "Project built successfully!"
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: echo "Deploying to production..." && sleep 10
    - name: deployment completed
      run: echo "Deployment completed successfully!"
