on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - develop
env:
  GLOBAL_SECRET: $SECRET_TOKEN
jobs:
  install_packages:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production
    steps:
    - name: install
      run: echo "Installing dependencies..." && sleep 10
    - name: packeged installed
      run: echo "Dependencies installed successfully!"
    if: ($CI_COMMIT_BRANCH == "main")
  lint_code:
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production
    steps:
    - name: lint
      run: echo "linting code..." && sleep 10
    - name: packeged installed
      run: echo "Code linted successfully!"
    if: ($CI_COMMIT_BRANCH == "main")
  build_project:
    runs-on: ubuntu-latest
    steps:
    - name: create build
      run: echo "Building project..." && sleep 10
    - name: build created
      run: echo "Project built successfully!"
    if: ($CI_COMMIT_BRANCH == "master")
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: echo "Deploying to production..." && sleep 10
    - name: deployment completed
      run: echo "Deployment completed successfully!"
    if: ($CI_COMMIT_BRANCH == "main")
